### ISSUE TITLE
Include packages file for easy install of dependencies?

### ISSUE THREAD

**Issue by kameelyan** [tritoch/SpoilerSeason#1]
I don't really work in python, but the idea behind this script is great. Is there an easy command line to install all the dependencies, and if not, can one be setup?

**Comment by dev-id** [comment]
Thanks, I believe `pip` has you covered.

`pip install datetime requests feedparser`

The rest are installed (or can be through pip) in newest Python 2.7

**Comment by kameelyan** [comment]
I saw you pushed out "first time run" updates, maybe that's what I was having issues with. I was able to re-clone the repo today and run it with no problems.

**Comment by dev-id** [comment]
Yup went ahead and started from scratch, noticed a few issues.  Glad you're up and going.  Fixed by 7456fc9
